# Generated by Django 4.2.1 on 2023-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='picture',
            field=models.ImageField(blank=True, default='ihame', null=True, upload_to='img'),
        ),
    ]
